/*
 * @name Bookfiler™ Recognize Module
 * @author Branden Lee
 * @version 1.00
 * @license GNU LGPL v3
 * @brief text recognition.
 */

#ifndef BOOKFILER_RECOGNIZE_CONFIG_H
#define BOOKFILER_RECOGNIZE_CONFIG_H

#define BOOKFILER_RECOGNIZE_DEBUG 1
#define BOOKFILER_RECOGNIZE_MODEL_ADD_PATHS 1
#define BOOKFILER_RECOGNIZE_MODEL_REQUEST_RECOGNIZE 1
#define BOOKFILER_RECOGNIZE_MODEL_RECOGNIZE_DONE_DEBUG 0
#define BOOKFILER_RECOGNIZE_MODEL_TO_STATEMENT_TABLE_DEBUG 0
#define BOOKFILER_RECOGNIZE_MODEL_TO_STATEMENT_TABLE_DEBUG2 0

#endif // BOOKFILER_RECOGNIZE_CONFIG_H
